FROM gcc as builder

WORKDIR /opt/cerver

# cerver
COPY . .
RUN make TYPE=test -j4 && make TYPE=test -j4 test

############
FROM ubuntu:bionic

# install cerver
COPY --from=builder /opt/cerver/bin/libcerver.so /usr/local/lib/
COPY --from=builder /opt/cerver/include/cerver /usr/local/include/cerver

# install app
COPY --from=builder /opt/cerver/test/bin/app/libapp.so /usr/local/lib/
COPY --from=builder /opt/cerver/test/app/*.h /usr/local/include/app/

RUN ldconfig

# cerver
WORKDIR /home/cerver
COPY --from=builder /opt/cerver/test/bin ./bin

CMD ["./bin/cerver/ping"]