FROM gcc as builder

RUN apt-get update && apt-get install -y libssl-dev

# build cerver with development flags
WORKDIR /opt/cerver
COPY ./src .
COPY ./include .
RUN make -j4

############
FROM ermiry/cmongo:dev

# cerver files
COPY --from=builder /opt/cerver/bin/libcerver.so /usr/local/lib/
COPY --from=builder /opt/cerver/include/cerver /usr/local/include/cerver

RUN ldconfig

CMD ["/bin/bash"]
